[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncate_to_repo = false
truncation_length = 10

[hostname]
format = "@[$hostname]($style) "

[username]
format = "[$user]($style)"